---
galaxy_info:
  author: Galaxy Europe
  description: installation of HTCondor from the official repository for RHEL systems
  company: Galaxy Europe
  license: GPL-3.0
  min_ansible_version: 2.11
  role_name: htcondor
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - system
dependencies: []
allow_duplicates: true
